trigger:
- master  # Change this to 'main' if your GitHub default branch is main

pool:
  name: 'Default'

steps:
# We removed JavaToolInstaller and went straight to Maven
- task: Maven@3
  displayName: 'Execute Maven Build and Automation Tests'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    
    # CHANGE THESE THREE LINES: Tell Azure to use your local system's JAVA_HOME
    javaHomeOption: 'path'
    jdkDirectory: '$(JAVA_HOME)' 
    jdkArchitectureOption: 'x64'
    
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package'